name: build-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        c_compiler: [gcc, clang]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4
    
    - name: Install deps
      run: |
        sudo apt-get -y update && sudo apt-get -y install automake libtool build-essential
       
    - name: Install libuv
      run: |
        wget https://github.com/libuv/libuv/archive/refs/tags/v1.49.2.tar.gz
        tar -xvzf v1.49.2.tar.gz
        cd libuv-1.49.2
        sh autogen.sh
        ./configure
        make
        make check
        sudo make install

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -S ${{ github.workspace }}

    - name: Build
      run: |
        cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      if: always()
      run: |
        if [ -d "${{ steps.strings.outputs.build-output-dir }}/test" ]; then
          ctest --test-dir ${{ steps.strings.outputs.build-output-dir }}/test --build-config ${{ matrix.build_type }}
        else
          echo "Test directory not found. Skipping tests."
        fi

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: kse-executable
        path: ${{ steps.strings.outputs.build-output-dir }}/kse