name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build_type: [Release]
        c_compiler: [gcc]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++

    steps:
    - uses: actions/checkout@v4

    - name: Download Boost Artifact
      id: boost-artifact
      uses: actions/download-artifact@v3
      with:
        name: boost-${{ matrix.os }}
        path: boost-artifact
      continue-on-error: true

    - name: Extract Boost Artifact
      if: steps.boost-artifact.outcome == 'success'
      run: |
        echo "Extracting Boost from artifact..."
        if [ "${{ runner.os }}" == "Linux" ]; then
          mkdir -p /home/runner/work/kse/kse/boost-install-dir
          unzip boost-artifact/boost-install-dir.zip -d /home/runner/work/kse/kse/boost-install-dir
        else
          mkdir -p C:/boost-install-dir
          powershell -Command "Expand-Archive -Path boost-artifact/boost-install-dir.zip -DestinationPath C:/boost-install-dir"

    - name: Install Boost (Linux)
      if: runner.os == 'Linux' && steps.boost-artifact.outcome != 'success'
      run: |
        curl -L https://boostorg.jfrog.io/artifactory/main/release/1.87.0/source/boost_1_87_0.tar.gz -o boost.tar.gz
        tar -xf boost.tar.gz
        cd boost_1_87_0
        ./bootstrap.sh
        ./b2 install --prefix=/home/runner/work/kse/kse/boost-install-dir
        cd /home/runner/work/kse/kse/boost-install-dir
        zip -r ../boost-install-dir.zip .
        ls

    - name: Save Boost as Artifact
      if: steps.boost-artifact.outcome != 'success'
      uses: actions/upload-artifact@v3
      with:
        name: boost-${{ matrix.os }}
        path: |
          /home/runner/work/kse/kse/boost-install-dir.zip
        retention-days: 90

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        echo "boost-root=/home/runner/work/kse/kse/boost-install-dir" >> "$GITHUB_OUTPUT"
       

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DBOOST_ROOT=${{ steps.strings.outputs.boost-root }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      if: always()
      run: |
        if [ -d "${{ steps.strings.outputs.build-output-dir }}/test" ]; then
          ctest --test-dir ${{ steps.strings.outputs.build-output-dir }}/test --build-config ${{ matrix.build_type }}
        else
          echo "Test directory not found. Skipping tests."