name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Restore Boost Cache
      id: boost-cache
      uses: actions/cache@v3
      with:
        path: |
          ~/boost-install-dir
          C:\boost-install-dir
        key: ${{ runner.os }}-boost-1.87
        restore-keys: |
          ${{ runner.os }}-boost-

    - name: Install Boost (Linux)
      if: runner.os == 'Linux' && !steps.boost-cache.outputs.cache-hit
      run: |
        curl -L https://boostorg.jfrog.io/artifactory/main/release/1.87.0/source/boost_1_87_0.tar.gz -o boost.tar.gz
        tar -xf boost.tar.gz
        cd boost_1_87_0
        ./bootstrap.sh
        ./b2 install --prefix=~/boost-install-dir

    - name: Install Boost (Windows)
      if: runner.os == 'Windows' && !steps.boost-cache.outputs.cache-hit
      run: |
        curl -L https://boostorg.jfrog.io/artifactory/main/release/1.87.0/source/boost_1_87_0.zip -o boost.zip
        tar -xf boost.zip
        cd boost_1_87_0
        ./bootstrap.bat
        ./b2.exe install --prefix=C:\boost-install-dir

    - name: Save Boost Cache
      if: steps.boost-cache.outputs.cache-hit == true
      uses: actions/cache@v3
      with:
        path: |
          ~/boost-install-dir
          C:\boost-install-dir
        key: ${{ runner.os }}-boost-1.87

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}/test
      run: ctest --build-config ${{ matrix.build_type }}
