name: Valgrind Memory Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  valgrind-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Restore Boost Cache
      id: boost-cache
      uses: actions/cache@v3
      with:
        path: |
          ~/boost-install-dir
          C:\boost-install-dir
        key: ${{ runner.os }}-boost-1.87
        restore-keys: |
          ${{ runner.os }}-boost-

    - name: Install Boost (Linux)
      if: steps.boost-cache.outputs.cache-hit == false
      run: |
        curl -L https://boostorg.jfrog.io/artifactory/main/release/1.87.0/source/boost_1_87_0.tar.gz -o boost.tar.gz
        tar -xf boost.tar.gz
        cd boost_1_87_0
        ./bootstrap.sh
        ./b2 install --prefix=~/boost-install-dir

    - name: Save Boost Cache
      if: steps.boost-cache.outputs.cache-hit == false
      uses: actions/cache@v3
      with:
        path: |
          ~/boost-install-dir
          C:\boost-install-dir
        key: ${{ runner.os }}-boost-1.87

    - name: Install Valgrind
      run: sudo apt-get update && sudo apt-get install -y valgrind

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        echo "boost-root=~/boost-install-dir" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DBOOST_ROOT=${{ steps.strings.outputs.boost-root }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

    - name: Test with Valgrind
      run: |
        valgrind --leak-check=full --track-origins=yes --verbose --error-exitcode=1 --log-file=valgrind_output.txt ${{ steps.strings.outputs.build-output-dir }}/test/test
        valgrind --leak-check=full --track-origins=yes --verbose --error-exitcode=1 --log-file=valgrind_output_lfq.txt ${{ steps.strings.outputs.build-output-dir }}/src/utils/lock_free_queue_example
        valgrind --leak-check=full --track-origins=yes --verbose --error-exitcode=1 --log-file=valgrind_output_mp.txt ${{ steps.strings.outputs.build-output-dir }}/src/utils/memory_pool_example
        valgrind --leak-check=full --track-origins=yes --verbose --error-exitcode=1 --log-file=valgrind_output_lg.txt ${{ steps.strings.outputs.build-output-dir }}/src/utils/logger_example
      continue-on-error: true

    - name: Upload Valgrind outputs
      uses: actions/upload-artifact@v3
      with:
        name: valgrind-logs
        path: |
          valgrind_output.txt
          valgrind_output_lfq.txt
          valgrind_output_mp.txt
          valgrind_output_lg.txt
